In [2]:
import numpy as np

In [3]:
in_arr = np.array([[[2, 4, 2], [4, 0, 2],[9,0,3]]])

In [4]:
print ("Input array : ", in_arr) 
print("Shape of input array : ", in_arr.shape)  

Input array :  [[[2 4 2]
  [4 0 2]
  [9 0 3]]]
Shape of input array :  (1, 3, 3)


In [5]:
out_arr = np.squeeze(in_arr)

In [6]:
print ("output squeezed array : ", out_arr)
print("Shape of output array : ", out_arr.shape) 

output squeezed array :  [[2 4 2]
 [4 0 2]
 [9 0 3]]
Shape of output array :  (3, 3)
