In [1]:
import numpy as np

In [2]:
arr=np.array([1,8,99,0,37,54,12,67,6])

In [3]:
arr

array([ 1,  8, 99,  0, 37, 54, 12, 67,  6])

In [4]:
k=5

k = no of smallest values to find in the array

In [5]:
arr1=np.sort(arr)

In [6]:
arr1

array([ 0,  1,  6,  8, 12, 37, 54, 67, 99])

In [7]:
arr1[:k]

array([ 0,  1,  6,  8, 12])

k smallest values in the array are (0,1,6,8,12) ; 
where k is 5